## Perceptron

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [3]:
def sigmoid_derivative(x):
    return x * (1-x)

In [4]:
training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])

training_outputs = np.array([[0,1,1,0]]).T

In [5]:
np.random.seed(1)

synaptic_weights = 2 * np.random.random((3,1)) - 1
print("Starting synaptic weights are:\n",synaptic_weights)

Starting synaptic weights are:
 [[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [6]:
for iteration in range(100000):
    input_layer = training_inputs
    
    outputs = sigmoid(np.dot(input_layer,synaptic_weights))
    error = training_outputs - outputs
    
    adjustments = error * sigmoid_derivative(outputs)
    synaptic_weights += np.dot(input_layer.T,adjustments)
    
print("Synaptic weights:\n",synaptic_weights)
print("Outputs after training:\n",outputs)

Synaptic weights:
 [[12.00870061]
 [-0.2044116 ]
 [-5.8002822 ]]
Outputs after training:
 [[0.00301758]
 [0.99753723]
 [0.99799161]
 [0.00246109]]


## Neural Networks

In [7]:
class NeuralNetwork():
    def __init__(self):
        np.random.seed(1)
        
        self.synaptic_weights = 2 * np.random.random((3,1)) - 1
        
    def sigmoid(self,x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self,x):
        return x * (1 - x)
    
    def train(self,training_inputs, training_outputs, training_iterations):
        for iteration in range(training_iterations):
            output = self.think(training_inputs)
            
            error = training_outputs - output
            adjustments = np.dot(training_inputs.T, error * self.sigmoid_derivative(output))
            
            self.synaptic_weights += adjustments
    
    def think(self,inputs):
        
        inputs = inputs.astype(float)
        outputs = self.sigmoid(np.dot(inputs,self.synaptic_weights))
        
        return outputs

In [9]:
if __name__ == "__main__":
    neural_network = NeuralNetwork()
    print("Random synaptic weights:\n",neural_network.synaptic_weights)
    
    training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])

    training_outputs = np.array([[0,1,1,0]]).T
    
    neural_network.train(training_inputs,training_outputs,20000)
    
    print("Synaptic weights after training:\n",neural_network.synaptic_weights)
    
    A = str(input("Input 1:"))
    B = str(input("Input 2:"))
    C = str(input("Input 3:"))
    
    print("New situation: Data = \n",A,B,C)
    print("New output:\n")
    print(neural_network.think(np.array([A,B,C]).T))

Random synaptic weights:
 [[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Synaptic weights after training:
 [[10.38040701]
 [-0.20641179]
 [-4.98452047]]
Input 1:1
Input 2:1
Input 3:1
New situation: Data = 
 1 1 1
New output:

[0.99445597]
